services:
  web:
    build: .
    container_name: aianalyzer_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 4000
    volumes:
      - ./app:/app/app
    ports:
      - "4000:4000"
    environment:
      DOCUMENT_SERVICE_URL: http://host.docker.internal:8000
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/aianalyzer
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DEBUG: "1"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: aianalyzer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aianalyzer
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: aianalyzer_redis
    restart: always
#    ports:
#      - "6379:6379"

  worker:
    build: .
    container_name: aianalyzer_worker
    command: celery -A app.celery_app.celery_app worker --loglevel=info --queues=default,document_processing
    volumes:
      - ./app:/app/app
    environment:
      DOCUMENT_SERVICE_URL: http://host.docker.internal:8000
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/aianalyzer
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  pgdata: 